### ISSUE TITLE
try to install it using cmake , error occurs

### ISSUE THREAD

**Issue by wanghetongtt** [ipa320/cob_object_perception#51] opened 2017-06-08 15:55 UTC
Could not find a package configuration file provided by "cob_3d_features"
  with any of the following names:

    cob_3d_featuresConfig.cmake
    cob_3d_features-config.cmake

**Comment by ipa-rmb** [comment] 2017-06-08 16:17
Did you also clone https://github.com/ipa320/cob_environment_perception.git into your source repository? It seems like that is missing.

**Comment by wanghetongtt** [comment] 2017-06-09 14:36
thank you for the reply, i add this to the source along with some dependency and after the build, this error occur, any idea what this is ?
![screenshot from 2017-06-09 10 36 03](https://user-images.githubusercontent.com/26974450/26980218-7b7d7bce-4cff-11e7-8f36-a5f610455822.png)

**Comment by ipa-rmb** [comment] 2017-06-12 07:06
did you run rosdep install to install all the dependencies? The error says that scons is missing, which is listed as a depency that rosdep would install.

Go to your catkin workspace directory (i.e. the folder with build, devel and src folders inside) and type

`rosdep install --from-path src/ -y -i`

This installs all necessary dependencies (there will be many more if you start installing things manually).

**Comment by wanghetongtt** [comment] 2017-06-12 14:50
it works for that error, but new problem occurs.... so it keeps telling me that undefined reference to cv:: so clearly it does not recognize my opencv package anymore, how do i fix that?
![screenshot from 2017-06-12 10 49 26](https://user-images.githubusercontent.com/26974450/27039739-d4b26010-4f5c-11e7-9830-dd994a2d3c00.png)
![screenshot from 2017-06-12 10 50 31](https://user-images.githubusercontent.com/26974450/27039773-f86ed588-4f5c-11e7-99e5-ca23c58b7b04.png)

**Comment by ipa-rmb** [comment] 2017-06-13 05:46
Are you using Ubuntu 14.04 with ROS Indigo and OpenCV 2.4.x or something else? The software is not yet fully ported to newer versions.

**Comment by fmessmer** [comment] 2017-07-03 14:47
first problem is duplicate of #50 (source dependecies)
second problem is documented in #47 (kinetic migration, cv incompatibility)

Thus, I guess this can be closed...@ipa-rmb

**Closed as completed** 2017-07-04 12:16 UTC
